export const people = [
    {
      name: 'Godfrey Turqueza',
      email: 'godfreyturqz@gmail.com',
      contact: '0926-032-9025',
      gender: 'Male',
      address: '0768 Washington st. El rosario Village, Mabalacat, Pampanga',
    },
    {
      name: 'Godfrey Turqueza',
      email: 'godfreyturqz@gmail.com',
      contact: '0926-032-9025',
      gender: 'Male',
      address: '0768 Washington st. El rosario Village, Mabalacat, Pampanga',
    },
    {
      name: 'Godfrey Turqueza',
      email: 'godfreyturqz@gmail.com',
      contact: '0926-032-9025',
      gender: 'Male',
      address: '0768 Washington st. El rosario Village, Mabalacat, Pampanga',
    },
    {
      name: 'Godfrey Turqueza',
      email: 'godfreyturqz@gmail.com',
      contact: '0926-032-9025',
      gender: 'Male',
      address: '0768 Washington st. El rosario Village, Mabalacat, Pampanga',
    },
    {
      name: 'Godfrey Turqueza',
      email: 'godfreyturqz@gmail.com',
      contact: '0926-032-9025',
      gender: 'Male',
      address: '0768 Washington st. El rosario Village, Mabalacat, Pampanga',
    },
    {
      name: 'Godfrey Turqueza',
      email: 'godfreyturqz@gmail.com',
      contact: '0926-032-9025',
      gender: 'Male',
      address: '0768 Washington st. El rosario Village, Mabalacat, Pampanga',
    },
    {
      name: 'Godfrey Turqueza',
      email: 'godfreyturqz@gmail.com',
      contact: '0926-032-9025',
      gender: 'Male',
      address: '0768 Washington st. El rosario Village, Mabalacat, Pampanga',
    },
    {
      name: 'Godfrey Turqueza',
      email: 'godfreyturqz@gmail.com',
      contact: '0926-032-9025',
      gender: 'Male',
      address: '0768 Washington st. El rosario Village, Mabalacat, Pampanga',
    },
    {
      name: 'Godfrey Turqueza',
      email: 'godfreyturqz@gmail.com',
      contact: '0926-032-9025',
      gender: 'Male',
      address: '0768 Washington st. El rosario Village, Mabalacat, Pampanga',
    },
    {
      name: 'Godfrey Turqueza',
      email: 'godfreyturqz@gmail.com',
      contact: '0926-032-9025',
      gender: 'Male',
      address: '0768 Washington st. El rosario Village, Mabalacat, Pampanga',
    },
    {
      name: 'Godfrey Turqueza',
      email: 'godfreyturqz@gmail.com',
      contact: '0926-032-9025',
      gender: 'Male',
      address: '0768 Washington st. El rosario Village, Mabalacat, Pampanga',
    },
    {
      name: 'Godfrey Turqueza',
      email: 'godfreyturqz@gmail.com',
      contact: '0926-032-9025',
      gender: 'Male',
      address: '0768 Washington st. El rosario Village, Mabalacat, Pampanga',
    },
    {
      name: 'Godfrey Turqueza',
      email: 'godfreyturqz@gmail.com',
      contact: '0926-032-9025',
      gender: 'Male',
      address: '0768 Washington st. El rosario Village, Mabalacat, Pampanga',
    },
    {
      name: 'Godfrey Turqueza',
      email: 'godfreyturqz@gmail.com',
      contact: '0926-032-9025',
      gender: 'Male',
      address: '0768 Washington st. El rosario Village, Mabalacat, Pampanga',
    },
    {
      name: 'Godfrey Turqueza',
      email: 'godfreyturqz@gmail.com',
      contact: '0926-032-9025',
      gender: 'Male',
      address: '0768 Washington st. El rosario Village, Mabalacat, Pampanga',
    },
    {
      name: 'Godfrey Turqueza',
      email: 'godfreyturqz@gmail.com',
      contact: '0926-032-9025',
      gender: 'Male',
      address: '0768 Washington st. El rosario Village, Mabalacat, Pampanga',
    },
    {
      name: 'Godfrey Turqueza',
      email: 'godfreyturqz@gmail.com',
      contact: '0926-032-9025',
      gender: 'Male',
      address: '0768 Washington st. El rosario Village, Mabalacat, Pampanga',
    },
    {
      name: 'Godfrey Turqueza',
      email: 'godfreyturqz@gmail.com',
      contact: '0926-032-9025',
      gender: 'Male',
      address: '0768 Washington st. El rosario Village, Mabalacat, Pampanga',
    },
    {
      name: 'Godfrey Turqueza',
      email: 'godfreyturqz@gmail.com',
      contact: '0926-032-9025',
      gender: 'Male',
      address: '0768 Washington st. El rosario Village, Mabalacat, Pampanga',
    },
    {
      name: 'Godfrey Turqueza',
      email: 'godfreyturqz@gmail.com',
      contact: '0926-032-9025',
      gender: 'Male',
      address: '0768 Washington st. El rosario Village, Mabalacat, Pampanga',
    },
    {
      name: 'Godfrey Turqueza',
      email: 'godfreyturqz@gmail.com',
      contact: '0926-032-9025',
      gender: 'Male',
      address: '0768 Washington st. El rosario Village, Mabalacat, Pampanga',
    },
    {
      name: 'Godfrey Turqueza',
      email: 'godfreyturqz@gmail.com',
      contact: '0926-032-9025',
      gender: 'Male',
      address: '0768 Washington st. El rosario Village, Mabalacat, Pampanga',
    },
    {
      name: 'Godfrey Turqueza',
      email: 'godfreyturqz@gmail.com',
      contact: '0926-032-9025',
      gender: 'Male',
      address: '0768 Washington st. El rosario Village, Mabalacat, Pampanga',
    },
    {
      name: 'Godfrey Turqueza',
      email: 'godfreyturqz@gmail.com',
      contact: '0926-032-9025',
      gender: 'Male',
      address: '0768 Washington st. El rosario Village, Mabalacat, Pampanga',
    },
    {
      name: 'Godfrey Turqueza',
      email: 'godfreyturqz@gmail.com',
      contact: '0926-032-9025',
      gender: 'Male',
      address: '0768 Washington st. El rosario Village, Mabalacat, Pampanga',
    },
    {
      name: 'Godfrey Turqueza',
      email: 'godfreyturqz@gmail.com',
      contact: '0926-032-9025',
      gender: 'Male',
      address: '0768 Washington st. El rosario Village, Mabalacat, Pampanga',
    },
    {
      name: 'Godfrey Turqueza',
      email: 'godfreyturqz@gmail.com',
      contact: '0926-032-9025',
      gender: 'Male',
      address: '0768 Washington st. El rosario Village, Mabalacat, Pampanga',
    },
    {
      name: 'Godfrey Turqueza',
      email: 'godfreyturqz@gmail.com',
      contact: '0926-032-9025',
      gender: 'Male',
      address: '0768 Washington st. El rosario Village, Mabalacat, Pampanga',
    },
    {
      name: 'Godfrey Turqueza',
      email: 'godfreyturqz@gmail.com',
      contact: '0926-032-9025',
      gender: 'Male',
      address: '0768 Washington st. El rosario Village, Mabalacat, Pampanga',
    },
    {
      name: 'Godfrey Turqueza',
      email: 'godfreyturqz@gmail.com',
      contact: '0926-032-9025',
      gender: 'Male',
      address: '0768 Washington st. El rosario Village, Mabalacat, Pampanga',
    },
]