export const INDEX = '/'
export const SIGN_UP = '/signup'
export const SIGN_IN = '/signin'
export const SIGN_OUT = '/signout'
export const PROFILE = '/profile'
export const DASHBOARD = '/dashboard'
export const SETTINGS = '/settings'
